openapi: 3.0.3
info:
  description: WMS Circulation API
  version: 1.0.0
  title: WMS Circulation API
servers:
  - url: 'https://{registryID}.share.worldcat.org/circ'
    variables:
      registryId:
        default: sd00
        description: WorldCat Registry ID for institution whose data is being accessed.    
security:
  - wms_circulation_auth:
    - WMS_Circulation
paths:
  /pulllist/{branchId}:
    get:
      tags:
        - Pull list
      summary: 'Retrieve a pull list for a specific branch'
      description: 'Retrieve a pull list for a specific branch'
      operationId: get-pulllist
      parameters:
        - name: branchId
          in: path
          description: WorldCat Registry Id of branch to get a pull list for
          schema:
            type: integer
          required: true                  
      responses:
        '200':
          description: Successful read of pulllist
          content:
            application/atom+xml:
              schema:
                type: object            
              examples:
                success-read-pull-list-atom-xml: 
                  $ref: '#/components/examples/success-read-pull-list-atom-xml'          
            application/xml:
              schema:
                type: object            
              examples:
                success-read-pull-list-xml: 
                  $ref: '#/components/examples/success-read-pull-list-xml'            
            application/atom+json:
              schema:
                type: object            
              examples:
                success-read-pull-list-atom-json: 
                  $ref: '#/components/examples/success-read-pull-list-atom-json'          
            application/json:
              schema:
                type: object            
              examples:
                success-read-pull-list: 
                  $ref: '#/components/examples/success-read-pull-list'                    
        '400':
          description: Invalid query. The request was unacceptable, often due to missing a required parameter.
          content:
            application/json:
              schema:
                type: object            
              examples:
                missing-query-parameter:
                  $ref: '#/components/examples/missing-query-parameter'
                missing-query-parameter-value:
                  $ref: '#/components/examples/missing-query-parameter-value'
              
        '405':
          description: 'Method not supported, see response Allow header'
          content:
            application/json:
              schema:
                type: object            
              example:
                $ref: '#/components/examples/method-not-allowed-error'               
        '500':
          description: 'Something went wrong (hopfully rare) - please try again'
          content:
            application/json:
              schema:
                type: object
  /items/{itemIdentifier}/routing/pull:
    post:
      tags:
        - Items
      summary: 'Mark a specific Item as pulled'
      description: 'Mark a specific Item as pulled'
      operationId: mark-item-pulled
      parameters:
        - name: itemIdentifier
          in: path
          description: The piece designation or item id for the item
          schema:
            type: string
          required: true
      requestBody:
        description: Pull item
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/ItemRoute' 
            examples:
              pull-item:
                $ref: '#/components/examples/pull-item'
              pull-freetext-hold:
                $ref: '#/components/examples/pull-freetext-hold'                             
      responses:
        '200':
          description: Successful Pull item
          content:          
            application/json:
              schema:
                type: object            
              examples:
                success-pull-item: 
                  $ref: '#/components/examples/success-pull-item'
                success-pull-item-route: 
                  $ref: '#/components/examples/success-pull-item-route'
                success-pull-item-scheduled: 
                  $ref: '#/components/examples/success-pull-item-scheduled'                                                        
        '400':
          description: Invalid query. The request was unacceptable, often due to missing a required parameter.
          content:
            application/json:
              schema:
                type: object            
              examples:
                missing-item:
                  $ref: '#/components/examples/missing-item'
                withdrawn-item:
                  $ref: '#/components/examples/withdrawn-item'
                checkedout-item:
                  $ref: '#/components/examples/checkedout-item'
                lost-item:
                  $ref: '#/components/examples/lost-item'
                unknown-item:
                  $ref: '#/components/examples/unknown-item'
                invalid-branch:
                  $ref: '#/components/examples/invalid-branch'                                                                        
              
        '405':
          description: 'Method not supported, see response Allow header'
          content:
            application/json:
              schema:
                type: object            
              example:
                $ref: '#/components/examples/method-not-allowed-error'               
        '500':
          description: 'Something went wrong (hopfully rare) - please try again'
          content:
            application/json:
              schema:
                type: object  
  /items/{itemIdentifier}/routing/inventories:
    post:
      tags:
        - Items
      summary: 'Retrieve a pull list for a specific branch'
      description: 'Retrieve a pull list for a specific branch'
      operationId: mark-item-inventoried
      parameters:
        - name: itemIdentifier
          in: path
          description: The piece designation or item id for the item
          schema:
            type: string
          required: true                  
      responses:
        '200':
          description: Successful inventory item
          content:                     
            application/json:
              schema:
                $ref: '#/components/schemas/Item'            
              examples:
                success-reshelve: 
                  $ref: '#/components/examples/success-reshelve'
                success-reshelve-route-different-branch: 
                  $ref: '#/components/examples/success-reshelve-route-different-branch' 
                success-reshelve-route-different-institution: 
                  $ref: '#/components/examples/success-reshelve-route-different-institution'                  
                success-pull-item: 
                  $ref: '#/components/examples/success-pull-item'
                success-pull-item-route: 
                  $ref: '#/components/examples/success-pull-item-route'
                success-pull-item-scheduled: 
                  $ref: '#/components/examples/success-pull-item-scheduled'                                      
        '400':
          description: Invalid query. The request was unacceptable, often due to missing a required parameter.
          content:
            application/json:
              schema:
                type: object            
              examples:
                missing-item:
                  $ref: '#/components/examples/missing-item'
                withdrawn-item:
                  $ref: '#/components/examples/withdrawn-item'
                checkedout-item:
                  $ref: '#/components/examples/checkedout-item'
                lost-item:
                  $ref: '#/components/examples/lost-item'
                unknown-item:
                  $ref: '#/components/examples/unknown-item'
                invalid-branch:
                  $ref: '#/components/examples/invalid-branch' 
              
        '405':
          description: 'Method not supported, see response Allow header'
          content:
            application/json:
              schema:
                type: object            
              example:
                $ref: '#/components/examples/method-not-allowed-error'               
        '500':
          description: 'Something went wrong (hopfully rare) - please try again'
          content:
            application/json:
              schema:
                type: object  
  /items/{itemIdentifier}/routing/usages:
    post:
      tags:
        - Items
      summary: 'Retrieve a pull list for a specific branch'
      description: 'Retrieve a pull list for a specific branch'
      operationId: mark-item-as-non-loan-return
      parameters:
        - name: itemIdentifier
          in: path
          description: The piece designation or item id for the item
          schema:
            type: string
          required: true                   
      responses:
        '200':
          description: Successful Non-Loan Return of Item
          content:                     
            application/json:
              schema:
                $ref: '#/components/schemas/Item'            
              examples:
                success-reshelve: 
                  $ref: '#/components/examples/success-reshelve'
                success-reshelve-route-different-branch: 
                  $ref: '#/components/examples/success-reshelve-route-different-branch' 
                success-reshelve-route-different-institution: 
                  $ref: '#/components/examples/success-reshelve-route-different-institution'                  
                success-pull-item: 
                  $ref: '#/components/examples/success-pull-item'
                success-pull-item-route: 
                  $ref: '#/components/examples/success-pull-item-route'
                success-pull-item-scheduled: 
                  $ref: '#/components/examples/success-pull-item-scheduled'                    
        '400':
          description: Invalid query. The request was unacceptable, often due to missing a required parameter.
          content:
            application/json:
              schema:
                type: object            
              examples:
                missing-item:
                  $ref: '#/components/examples/missing-item'
                withdrawn-item:
                  $ref: '#/components/examples/withdrawn-item'
                checkedout-item:
                  $ref: '#/components/examples/checkedout-item'
                lost-item:
                  $ref: '#/components/examples/lost-item'
                unknown-item:
                  $ref: '#/components/examples/unknown-item'
                invalid-branch:
                  $ref: '#/components/examples/invalid-branch' 
              
        '405':
          description: 'Method not supported, see response Allow header'
          content:
            application/json:
              schema:
                type: object            
              example:
                $ref: '#/components/examples/method-not-allowed-error'               
        '500':
          description: 'Something went wrong (hopfully rare) - please try again'
          content:
            application/json:
              schema:
                type: object                                                       
  /holds/{identifier}/forward:
    post:
      tags:
        - Holds
      summary: 'Forward a Hold on an item'
      description: 'Forward a Hold on an item'
      operationId: forward-hold
      parameters:
        - name: identifier
          in: path
          description: The identifier for the hold
          schema:
            type: string
          required: true                   
      responses:
        '200':
          description: Successful Forward of Hold
          content:                    
            application/json:
              schema:
                type: object            
              examples:
                success-forward-hold: 
                  $ref: '#/components/examples/success-forward-hold'                    
        '400':
          description: Invalid query. The request was unacceptable.
          content:
            application/json:
              schema:
                type: object                          
        '405':
          description: 'Method not supported, see response Allow header'
          content:
            application/json:
              schema:
                type: object            
              example:
                $ref: '#/components/examples/method-not-allowed-error'               
        '500':
          description: 'Something went wrong (hopfully rare) - please try again'
          content:
            application/json:
              schema:
                type: object  
components:
  securitySchemes:
    wms_circulation_auth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.oclc.org/token
          scopes:
            WMS_Circulation: perform all the operation in the WMS Circulation API
        authorizationCode:
          authorizationUrl: https://oauth.oclc.org/auth
          tokenUrl: https://oauth.oclc.org/token
          scopes:
            WMS_Circulation: perform all the operation in the WMS Circulation API
  schemas:
    ItemRoute:
      type: object
      properties:
        reason:
          type: object
          properties:
            reasonCode:
              type: string
              enum:
                - HOLD
                - SCHEDULED
                - RESHELVE
        dateRouted:
          type: string
          format: date-time
        destination:
          $ref: '#/components/schemas/Destination'
        item:
          $ref: '#/components/schemas/Item'
    Destination:
      type: object
      properties:
        ref:
          type: string
        branchId:
          type: integer
        branchName:
          type: string        
        institutionId:
          type: integer
        institutionName:
          type: string
    Item:
      type: object
      properties:
        ref:
          type: string
        ownerInstitution:
          type: object
          properties:
            institutionId:
              type: integer
            institutionName:
              type: string
        pieceDesignation:
          type: string
        callNumber:
          type: string
        itemRecordType:
          type: string
          enum:
            - SINGLE_PART
            - MULTI_PART
            - SERIAL
            - UNKNOWN    
        numberOfPieces:
          type: integer
        homeLocation:
          $ref: '#/components/schemas/HomeLocation'
    HomeLocation:
      type: object
      properties:
        shelvingLocationCode:
          type: string
        holdingLocation:
          type: object
          properties:
            holdingLocationCode:
              type: string
            location:
              type: object
              properties:
                ref:
                  type: string
                branchId:
                  type: integer
                branchName:
                  type: string
                institution:
                  type: object
                  properties:
                    institutionId:
                      type: integer
                    institutionName:
                      type: string                           
    BibliographicSummary:
      type: object
      properties:
        oclcNumber:
          type: integer
        title:
          type: string
        materialType:
          type: string
        author:
          type: string
        publisher:
          type: string
        publicationYear:
          type: string
        language:
          type: string
        edition:
          type: string                                                        
  examples:               
    unauthorized:
      summary: Error returned when valid API credentials not sent or invalid
      value: {"message": "Unauthorized"}
    forbidden:
      summary: Error returned when API credentials not for resource
      value: {"message": "Forbidden"}
    method-not-allowed-error:
      summary: Error when invalid HTTP method used
      value: {"title": "NOT_ALLOWED", "detail": "POST method not allowed"}
    not-acceptable-error:
      summary: Error when media type in Accept header not supported
      value: {"title": "NOT_ACCEPTABLE", "detail": "Media type application/xml not supported. Supported media types: application/json"}
    missing-query-parameter:
      summary: Error returned when required query parameter not sent
      value: {"type": "MISSING_QUERY_PARAMETER", "title": "Validation Failure", "detail": "Required String parameter 'q' is not present"}      
externalDocs:
  description: Find out more about WMS Circulation API
  url: 'https://www.oclc.org/developer/develop/web-services/wms-circulation-api.en.html'