  schemas:
    atom_results:
      type: object
      xml:
        namespace: "http://www.w3.org/2005/Atom"
        name: feed        
      properties:
        title:
          description: name of the results
          type: string
        id:
          description: ID for results set
          type: string
        updated:
          description: date query run
          type: string
        subtitle:
          description: query run
          type: string
        totalResults:
          description: Total number of results
          type: integer
          format: int32
          xml:
            namespace: "http://a9.com/-/spec/opensearch/1.1/"
            prefix: "opensearch"          
        itemsPerPage:
          description: number of items per page
          type: integer
          format: int32
          xml:
            namespace: "http://a9.com/-/spec/opensearch/1.1/"
            prefix: "opensearch"                  
        Query:
          description: query sent to API
          type: string
          xml:
            namespace: "http://a9.com/-/spec/opensearch/1.1/"
            prefix: "opensearch"
        link:
          items:          
            $ref: '#/components/schemas/Link'          
        entries:      
          description: actual results
          type: array
          items: 
            $ref: '#/components/schemas/atomEntry'          
    atomEntry:
      type: object
      xml:
        name: entry
      properties:
        author:
          description: Author from record
          type: string
        title:
          description: Title from record
          type: string
        link:
          description: Link to item in WorldCat.org
          type: array
          items:
            $ref: '#/components/schemas/Link'                    
        updated:
          description: Date record last updated
          type: string
        identifier:
          description: Identifier for item ISBN or ISSN
          type: string
          xml:
            namespace: "http://purl.org/dc/elements/1.1/"
            prefix: "dc"
        recordIdentifier:
          description: OCLC Number of LCCN for item
          type: string
          xml:
            namespace: "http://purl.org/oclc/terms/"
            prefix: "oclcterms"                                         
    rss_results:
      type: object
      xml:
        name: rss      
      properties:
        title:
          description: name of the results
          type: string
        link:
          description: Link for results set
          type: string
        description:
          description: query run
          type: string
        totalResults:
          description: Total number of results
          type: integer
          format: int32
          xml:
            namespace: "http://a9.com/-/spec/opensearch/1.1/"
            prefix: "opensearch"          
        itemsPerPage:
          description: number of items per page
          type: integer
          format: int32        
          xml:
            namespace: "http://a9.com/-/spec/opensearch/1.1/"
            prefix: "opensearch"          
        Query:
          description: query sent to API
          type: string
          xml:
            namespace: "http://a9.com/-/spec/opensearch/1.1/"
            prefix: "opensearch"          
        oslink:
          $ref: '#/components/schemas/Link'                    
        item:      
          description: actual results
          type: array
          items: 
            $ref: '#/components/schemas/rssItem'
    rssItem:
      type: object
      xml:
        name: item
      properties:
        author:
          description: Author from record
          type: string
        title:
          description: Title from record
          type: string
        link:
          description: Link to item in WorldCat.org
          type: array
          items:
            $ref: '#/components/schemas/Link'                    
        guid:
          description: Link to item in WorldCat.org
          type: string
        identifier:
          description: Identifier for item ISBN or ISSN
          type: string
          xml:
            namespace: "http://purl.org/dc/elements/1.1/"
            prefix: "dc"
        recordIdentifier:
          description: OCLC Number of LCCN for item
          type: string
          xml:
            namespace: "http://purl.org/oclc/terms/"
            prefix: "oclcterms"
    Link:
      type: object
      properties:
        href:
          type: string
          xml:
            attribute: true          
        rel:
          type: string
          enum:
            - self
            - alternate
            - first
            - last
            - search
          xml:
            attribute: true  
        type:
          type: string
          enum:
            - text/html
            - application/atom+xml 
          xml:
            attribute: true                           
    sru_results:
      type: object
      properties:
        title:
          description: Name of title
          type: string
        id:
          description: URL for title in API
          type: string
    marc:
      type: object
      properties:
        leader:
          type: string
          description: Marc Leader
        control_fields:
          type: array
          items:
            $ref: '#/components/schemas/control_field'                  
        datafields:
          type: array
          items:
            $ref: '#/components/schemas/subfield'
    control_field:
      type: object
      xml:
        name: control_field
      properties:
        tag:
          description: MARC tag
          type: string 
          xml:
            attribute: true
        control_field:
          type: string     
    data_field:
      type: object
      xml:
        name: datafield
      properties:
        ind1:
          description: first indicator
          type: integer
          xml:
            attribute: true
        ind2:
          description: second indicator
          type: integer
          xml:
            attribute: true          
        tag:
          description: MARC tag
          type: string 
          xml:
            attribute: true
        subfields:
          description: subfields
          type: array
          items:
            $ref: '#/components/schemas/subfield'                                          
    subfield:
      description: marc subfield
      type: object
      xml: 
        name: subfield
      properties:
        code:
          description: name of subfield
          type: string
          xml:
            attribute: true 
        subfield:
          type: string                                   
    dublin_core:
      type: object
      xml:
        name: oclcdcs
      properties:
        creator:
          description: Creator of material
          type: string
        date:
          description: Publication Date
          type: string
        descriptions:
          description: Description information
          type: array
          items:
            type: string
            xml:
              name: description              
        format:
          description: Format information
          type: string
        identifiers:
          description: Identifier information
          type: array
          items:
            type: string
            xml:
              name: identifiers  
        language:
          description: Language of material
          type: string
        publisher:
          description: Publisher of material
          type: string
        relations:
          description: relation information
          type: array
          items:
            type: string          
        subjects:
          description: Subject information
          type: array
          items:
            type: string
        title:
          description: Title of material
          type: string                        
        type:
          description: Type of material
          type: string 
        recordContentSource:
          description: record source
          type: string
        recordCreationDate:
          description: record creation date
          type: string        
        recordIdentifiers:
          description: record identifiers
          type: array
          items:
            $ref: '#/components/schemas/recordIdentifier'
        languageOfCataloging:
          description: language of cataloging
          type: object
        recordOCLCControlNumberCross-References:
          description: merged OCLC numbers
          type: array
          items:
            $ref: '#/components/schemas/recordOCLCControlNumberCross-Reference'        
        recordTranscribingAgency:
          description: who created the record 
          type: string
    relation:
      type: object                 
    recordIdentifier:
      type: object
    recordOCLCControlNumberCross-Reference:
      type: object 